version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  build_and_test_and_deploy:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Build start on `date`"
      - run: yarn install
      - run: yarn build
      - run: echo "Test start on `date`"
      - run: yarn test
      - add_ssh_keys:
          fingerprints:
            - "13:93:b9:49:ee:22:df:4d:71:ed:6c:6e:3c:27:ad:05"
      - run: npm install -g --silent gh-pages@2.0.1
      - run: git config user.email "ivanjaya@fivejack.com"
      - run: git config user.name "Ivan"
      - run: echo "Deploy start on `date`"
      - run: yarn deploy
workflows:
  build_and_test_and_deploy:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build_and_test_and_deploy:
          requires:
            - need-approval
