version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  build_and_test_and_deploy:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Build start on `date`"
      - run: yarn install
      - run: yarn build
      - run: echo "Test start on `date`"
      - run: yarn test
      - add_ssh_keys:
          fingerprints:
            - "e1:8c:70:c7:e0:12:70:ce:d8:96:4c:4e:a8:e6:0b:a5"
      - run: npm install -g --silent gh-pages@2.0.1
      - run: git config user.email "ivanjaya@fivejack.com"
      - run: git config user.name "Ivan"
      - run: echo "Deploy start on `date`"
      - run: gh-pages --dist workspace/out
workflows:
  build_and_test_and_deploy:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build_and_test_and_deploy:
          requires:
            - need-approval
